import type { WindowDefinition } from "@/features/window-system/types";

export const windowRegistry: Record<string, WindowDefinition> = {
  desktop: {
    id: "desktop",
    title: "Desktop",
    icon: "◉",
    initialWidth: 520,
    initialHeight: 340,
    defaultPosition: { x: 120, y: 90 },
  },
  projects: {
    id: "projects",
    title: "Projects",
    icon: "⌘",
    initialWidth: 560,
    initialHeight: 380,
    defaultPosition: { x: 180, y: 120 },
  },
  studio: {
    id: "studio",
    title: "Studio",
    icon: "♫",
    initialWidth: 540,
    initialHeight: 360,
    defaultPosition: { x: 220, y: 140 },
  },
  discography: {
    id: "discography",
    title: "Discography",
    icon: "◈",
    initialWidth: 560,
    initialHeight: 380,
    defaultPosition: { x: 260, y: 160 },
  },
  audioPlayer: {
    id: "audioPlayer",
    title: "Audio Player",
    icon: "♪",
    initialWidth: 560,
    initialHeight: 420,
    defaultPosition: { x: 300, y: 180 },
  },
  equipment: {
    id: "equipment",
    title: "Equipment",
    icon: "⚙",
    initialWidth: 560,
    initialHeight: 400,
    defaultPosition: { x: 320, y: 200 },
  },
  resume: {
    id: "resume",
    title: "Resume",
    icon: "◫",
    initialWidth: 500,
    initialHeight: 340,
    defaultPosition: { x: 260, y: 160 },
  },
  skills: {
    id: "skills",
    title: "Skills",
    icon: "◌",
    initialWidth: 540,
    initialHeight: 360,
    defaultPosition: { x: 300, y: 180 },
  },
  timeline: {
    id: "timeline",
    title: "Timeline",
    icon: "⧉",
    initialWidth: 520,
    initialHeight: 340,
    defaultPosition: { x: 340, y: 200 },
  },
  terminal: {
    id: "terminal",
    title: "Terminal",
    icon: ">",
    initialWidth: 520,
    initialHeight: 320,
    defaultPosition: { x: 300, y: 200 },
  },
  explorer: {
    id: "explorer",
    title: "Explorer",
    icon: "◌",
    initialWidth: 480,
    initialHeight: 300,
    defaultPosition: { x: 340, y: 220 },
  },
  settings: {
    id: "settings",
    title: "Settings",
    icon: "◎",
    initialWidth: 460,
    initialHeight: 320,
    defaultPosition: { x: 380, y: 240 },
  },
  aiLab: {
    id: "aiLab",
    title: "AI Lab",
    icon: "◍",
    initialWidth: 520,
    initialHeight: 360,
    defaultPosition: { x: 420, y: 260 },
  },
  debugConsole: {
    id: "debugConsole",
    title: "Debug Console",
    icon: "⌗",
    initialWidth: 560,
    initialHeight: 380,
    defaultPosition: { x: 420, y: 260 },
  },
};
